[tool.poetry]
name = "not-work-sandbox"
version = "0.1.0"
description = ""
authors = ["chanlee <chanlee@ps-analytics.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
